'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TaroProject.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _009829_ultra_glossy_silver_button_icon_arrows_arrow_ring1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("009829-ultra-glossy-silver-button-icon-arrows-arrow-ring1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _009906_ultra_glossy_silver_button_icon_arrows_triangle_circle_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("009906-ultra-glossy-silver-button-icon-arrows-triangle-circle-right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _021297_ultra_glossy_silver_button_icon_symbols_shapes_minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("021297-ultra-glossy-silver-button-icon-symbols-shapes-minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _021311_ultra_glossy_silver_button_icon_symbols_shapes_shape_stop_button_clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("021311-ultra-glossy-silver-button-icon-symbols-shapes-shape-stop-button-clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _074965_ultra_glossy_silver_button_icon_alphanumeric_crossing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("074965-ultra-glossy-silver-button-icon-alphanumeric-crossing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8853d2c9b4aa12993af4bee4ed12569e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8853d2c9b4aa12993af4bee4ed12569e", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back_of_card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_of_card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dark_Gothic_Wallpaper_For_Android_6067_Wallpaper__WallpaperLepi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dark Gothic Wallpaper For Android 6067 Wallpaper  WallpaperLepi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f88ceb69e69cccd8f8ba6c3afeee432b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f88ceb69e69cccd8f8ba6c3afeee432b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property giphy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("giphy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property goblin_tarot___card_back_b_by_vulpinoid_d4937mm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goblin_tarot___card_back_b_by_vulpinoid-d4937mm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenRoundedButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenRoundedButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ironbullc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ironbullc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Magic_Celtic_Music___The_Hooded_Man___Tarot() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Magic_Celtic_Music___The_Hooded_Man___Tarot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh_button_icon_63596() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh-button-icon-63596", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property serar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("serar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property slider_cards_bg_1024() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("slider_cards_bg_1024", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___10_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (10)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___11_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (11)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___12_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (12)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___13_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (13)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___14_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (14)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___15_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (15)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___16_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (16)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___17_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (17)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___18_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (18)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___19_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (19)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___20_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (20)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___21_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (21)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___22_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (22)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___23_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (23)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___24_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (24)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___25_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (25)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___26_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (26)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___27_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (27)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___28_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (28)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___29_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (29)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___30_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (30)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___31_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (31)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___32_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (32)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___33_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (33)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___34_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (34)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___35_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (35)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___5_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (5)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___6_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (6)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___7_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (7)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___8_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (8)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarot___9_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarot_ (9)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tumblr_ng5ih91a6y1qh6qw2o4_400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tumblr_ng5ih91a6y1qh6qw2o4_400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property xiii_tarot_by_nekro_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xiii-tarot-by-nekro-back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property xiii_tarot_by_nekro_back1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xiii-tarot-by-nekro-back1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
