using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tarot.Logic
{
    public static class CardDescriptions
    {
        public static Dictionary<int, string> CarotCartDescriptions = new Dictionary<int, string>()
        {
            {1, "The 3 of Wands refers to work, in an extremely positive way. Even if you don't work outside the home, it means that your efforts are seen, appreciated, and are well respected. Give yourself some credit."},
            {2, "The more accepting you can be of change of all sorts during this time, and the less you try to 'control' the better and the more comfortable this time will be for you. Often what you need to 'let go of' is some sort of self-limiting belief or attitude. Sometimes we just can't see how our attitudes are hurting us, and when that is true, this time period can be a wake-up call. The energy of this time is not just change or destruction; it is change or destruction followed by renewal. Even though one door may have closed, another is opening. Will you have the courage to step through?" },
            {3, "You've worked hard, and you are almost to the 'finish line' in some way. Don't quit now that you're almost finished! You're almost definitely in need of some well deserved rest and relaxation; don't be afraid to take it. You are getting closer to 'who you really are,' at your deepest levels." },
            {4, "If you are the one tending to jump to conclusions, you can put a stop to it. If others are making these kinds of decisions about you or about someone you care for, there is really very little you can do, apart from realizing that it's their problem, not yours." },
            {5, "It's important now for you to make time to meditate and contemplate and spend some time alone even if you are in a committed relationship and have nineteen children! Do not allow yourself to spend time in preoccupation and fear. Outward things will be going all right but what is of the most paramount importance is keeping your head on straight." },
            {6, "Although in general all your relationships are likely to be going quite well, you may need to look at your deeper personal issues and see if or how these are standing in your way. And if they are, how to work through them and integrate them. The idea now is to do what it takes to find balance, in yourself, in your relationships, and with your goals and aspirations."},
            {7, "Although this is a very positive card in a reading, it shows also a need to keep your wits about you, that although you deserve and should treat yourself to some fun, but know that you are still in a building up phase and now is not the time to rest completely on your laurels. This card can also sometimes mean that you will be moving your place of residence." },
            {8, "This is a time to rely on your intuition and your inner knowledge, rather than your conscious mind or intellect. Pay attention to your dreams. Synchronicities are likely now. When the High Priestess appears in a man's reading, she also often represents a woman that he will want badly; but whom he may not be able to get." },
            {9, "It's important for you to remember that no matter what your situation, that you always have options to choose from. First things first, don't let other people tell you that your options are limited. If you come to that conclusion, be sure that you are coming to it on your own. Regardless, it will be crucial to remember that you can free yourself from whatever restrictions are holding you back, at any time you choose to do so. You may have the feeling now that you are not in control of your life; sometimes this happens as a result of your own actions, but more often as a byproduct of inaction.  So, take action, take whatever steps you can to give yourself the feeling, however slight, of being in control. Even if that is merely making a choice on what you are going to have for dinner. Small steps are important, too." },
            {10, "This card is a definite good omen. You are probably already inclined to be thinking positively; this is a time to do so specifically. What are the changes that you would like to make or see in your life? Make a list. You can accomplish nearly anything that you set out to do now. Think big." },
            {11, "Things in general are very likely to be going very well for you. However, even though finances are likely to be in good shape when this card appears, that does not mean that you should lose focus on what is truly important in life, and money is not very high on that list. This is a good time to socialize, to meet new people, and to get out and about."},
            {12, "The Princess of Wands can also refer to a woman who has a lot of fire energy about her e.g. Aries, Leo, and Sagittarius. When not referring to a literal person, she stands for getting a lot accomplished, and often, a focus on work/career. The Princess is positive, uplifting energy. When she stands in for a woman in your life, she's a good friend, who is solidly on your side, even though she may seem a bit self-absorbed. If you are trying to conceive and this card appears, it's one of the most positive signs that there can be." },
            {13, "You are definitely in a more psychic and intuitive phase than usual, so it will be important for you to trust your instincts and your impressions, even if you don't know where they are coming from. Also, not that you need to be mistrusting, but it will be helpful for you to realize that when this card appears, it's possible that all is not what it seems. If you feel you can't trust someone, then you probably can't. Go with your gut. If you are waiting on an answer from someone, it may, unfortunately, take longer than you would like for it to. Try to stay patient." },
            {14, "This card depicts being upbeat, optimistic, and hopeful about your future - with good cause! You are likely to be feeling quite energetic and positive, or you very soon will be feeling that way. Aces also tell you that now is a good time to start something new. What will you begin?" },
            {15, " In general the 2 of Wands reminds us to stay mindful of the give-and-take required for all successful relationships. If things are feeling 'out of balance' for you in general now, know that they are about to get substantially better. Keep your eyes on the prize that you're looking for, metaphorically, and remain or get positive." },
            {16, "This card always reminds us that 'this too shall pass.' Whether that's good times or bad times, it passes. If suddenly you find yourself 'sitting on top of the world,' keep your perspective, as that too, like everything else, changes. Live in the now, count your blessings, and just realize that much of life is outside of your control, but that even that is okay. Roll with any changes, and think positively."},
            {17, "In general, this card would indicate new beginnings that have some deeper spiritual meaning - for example, starting a meditation practice or a relationship, as opposed to buying a new pair of shoes. The appearance of the fool can depict an important 'fresh start.'" },
            {18, "This is also a card that is very much about spirituality - everything from traditional religion to earth-centered spirituality and any other spiritual notion that you can conceive of. There may be a tension between your idea of spirituality and the 'right thing' and the ideas of others around you. Stand up for your own beliefs. The 'rules' and the 'system' of doing things are probably playing a major role now. Rituals of any sort will be helpful to you now, even if it's just 'a movie with friends every third Saturday.'" },
            {19, "In general, the 6 is about happiness and celebration. You are about to see some results for your hard work and efforts. Give yourself a break or treat yourself in some way. You have certainly earned it." },
            {20, "Just like with the Strength card, you may even more so be in the frame of mind that you need some time alone - don't be afraid to take it. Even if it's just a five minute walk around the house so that you can clear your head. This is also very much a card about 'trying very hard to do the right thing.' Just make sure that 'doing the right thing' includes doing what is right for you personally, and not just worrying about the wants and needs of others." },
            {21, "It's possible that there is an outdated attitude or wish that you need to let go of. Any sacrifice that you make will open up your life to something even more positive than what you 'let go of.' All in all this should be a thoughtful, reflective time, particularly if you are willing to look at if or how you might best serve your own interests by being willing to change."},
            {22, "Don't hesitate to make where you stand clear to people. Your thinking is clear, and you are likely to help someone out by spelling things out for them. This card can indicate that a change is coming - a positive change - in your personal or business life. This card also points toward being independent and thinking for yourself." },
            {23, "It is likely that some people/situations that you have counted on as being there for you may no longer be there in quite the same way. This doesn't have to be dire; change is the nature of life, and trying to prevent it is like trying to row upstream without a paddle. If  you have been building castles in the air this may be the time that some of them come crashing down to earth. That's only a problem if you let it be. You will be able to replace them with some more realistic and reachable dreams and goals if some fantasies fall apart this month. Dreaming is important, but it's also important to be living in reality too. You will get through this time just fine; particularly if you remember that you have all the resources you need, already inside you, to deal with life and to do what you need to do." },
            {24, "This card evokes the need for fairness, balance, and harmony. Operate in as balanced and reasonable a fashion as you can. This includes in how you think about and treat yourself. If you are directly involved with a court case, it is likely to be resolved, at least in large degree, in your favor." },
            {25, " People are going to be more attracted to you than usual (in every sense) and you are likely to find people on your doorstep, wanting your advice/your shoulder to cry on. This will be beneficial to you because you are now going to be able to see yourself more in the way that others see you - as someone with wisdom, and a lot to offer. So share your hard-won perspectives on life, know that your wisdom and caring is valuable." },
            {26, "It looks as though a kind, older man may be part of your scenario. This could be a work colleague, or your father or a father-type figure. Perhaps he will be interested in you romantically. If so, don't rule him out, just because of his age. You may feel that this man sort of 'rules with an iron fist' and that can be frustrating at times, but he is trying to help you to see that rules have their place and their reasons - and you will come out all the better for it. Above all else, this man teaches - without even trying, perhaps - the benefits of structure and logic ruling over the emotions and lesser desires."},
            {27, "You may notice many synchronicities, which point towards deep, spiritual events taking place regardless of the 'importance' of their superficial appearances. You should be finding that you have the knowledge, strength, and inspiration needed to meet your challenges. In general this is a very positive time for you." },
            {28, "In general this card points to determination and ambition, getting things done, and testing and proving what you've got. This is a sign that you should move forward with whatever you have in mind (and in your heart) and give it your best shot. Remember, though, that you'll need to use both your intellect and your heart, in order to be truly successful." },
            {29, "When this card appears, your need to believe in yourself is stronger than ever now. Hold your head up high, and have faith that you will end up in the place that is right for you. You may be thinking of making a career change. Know that you can be successful, if so." },
            {30, " It's possible when this card appears that you are feeling ambivalent about a relationship or situation in your life. It could be that your heart is telling you one thing, and your head, another. In general, the thing to do is (within the bounds of your morality) to follow your heart. Some people say there are only two modes that any of us are operating under at any time; and that's 'fear' or 'love.' When you can: choose love." },
            {31,"When the 9 of Wands comes up, the first and best step is often to take a deep breath and calm down. Don't let the things you are worried about overwhelm you. Take it one day at a time, one hour at a time, if you must. At least some of your worries will very likely turn out to be imaginary. Get very specific on what you are afraid of and pick it apart. What is the true likelihood of the worry actually happening? Comfort yourself, and if you need help, don't hesitate to ask for it. Asking for help is the mark of a strong person." },
            {32,"Sometimes the 10 of Wands indicates that you have been too successful and would be well-served by scaling back. You are probably tired, you've been working very hard, personally and professionally, and could use a break. Give yourself one." },
            {33," In general the King of Wands is a positive omen. Even when he does not represent a literal individual in your life, he signifies that men around you are generally supportive and think well of you. You will be feeling ambitious and goal-oriented, and furthermore, you will have the wherewithal to accomplish what you have in mind. Think positively. " },
            {34,"When this card appears, nothing seems to be moving ahead. Don't try to force things, as that is likely to backfire on you. Speaking metaphorically, sometimes our actions are all in the wrist, all you can do is put your best out there and see where it lands. You've put your best out there. Now wait. " },
            {35,"In general, this card indicates that things that you started some time ago are starting to come to fruition. It can also show a need for new things - new adventures, new approaches, and new ideas. The Page brings us positive energy. We must supply the follow-through, however. " },
        };
    }
}
